CREATE TABLE decks(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  title VARCHAR(100) NOT NULL,
  subject VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL,
  public VARCHAR(1) NOT NULL
);

CREATE TABLE users_decks(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  deck_id INT NOT NULL
);

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(320) NOT NULL,
  password VARCHAR(100) NOT NULL,
  register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (USERNAME)
);

CREATE TABLE cards(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  front VARCHAR(500) NOT NULL,
  back VARCHAR(500) NOT NULL,
  deck_id INT NOT NULL
);

CREATE TABLE cards_tags(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  tag_id INT NOT NULL,
  card_id INT NOT NULL
);

CREATE TABLE tags(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL
);
